# Jekyll options.
domain: http://dev.evansosenko.com/deck-spin-lifetime
baseurl: http://dev.evansosenko.com/deck-spin-lifetime
markdown: redcarpet
pygments: true
exclude:
  - CHANGELOG.md
  - LICENSE.txt
  - README.md
  - VERSION
  - Gemfile.lock
  - Gemfile
  - Rakefile
  - bower.json
  - bower_components
  - deck-*.zip

gems:
  - jekyll-assets
  - sass
  - coffee_script
  - bourbon

# Jekyll::AssetsPlugin options.
assets:
  baseurl: http://dev.evansosenko.com/deck-spin-lifetime/assets/
  sources:
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - bower_components
  compress:
    css: sass
    js: uglifier

# Default html tag to use for slides.
# Override per slide with {% slide tagname %}
slide_tag: section

# Set to true to load MathJax.
mathjax: true

# Use a cdn to load some libraries.
cdn_enabled: true
cdn:
  # [ url, fallback test, local asset fallback path ]
  libs:
    - [ "https://ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js", "!window.jQuery", "jquery/dist/jquery" ]
    - [ "https://ajax.googleapis.com/ajax/libs/webfont/1.5.0/webfont.js", "!window.WebFont", " webfontloader-min/webfont" ]

# Uncomment below to use Firebase as a deck remote.
firebase: https://deck-spin-lifetime.firebaseio.com/

# Uncomment below and add your Tracking ID and URL to enable Google Analytics.
# google_analytics:
#   id: UA-00000000-0
#   url: example.com

# Uncomment below and add your Piwik URL to enable Piwik.
# piwik: https://example.com/piwik/

# Uncomment below to configure social media.
# social:
#   facebook:
#     enabled: true
#   google:
#     enabled: true
#     gcfg:
#       lang: en-US
#       parsetags: onload
#   twitter:
#     enabled: true

# Uncomment below to enable deploy.
:deploy:
  # only :rsync supported
  :protocol: :rsync
  # domain name
  :server: ssh.evansosenko.com
  # remote username
  :user: webmaster
  # remote port
  :port: 22
  # path to remote folder where contents of _site should go
  # must have trailing slash
  :path: /usr/local/www/vhosts/evansosenko.com/htdocs/deck-spin-lifetime/
#   # site files and folders that should be uploaded but not synced
#   # remote content will not be removed from these files and folders
#   :upload_only:
#     - content/
