# This meta data should be filled out.
title: Effect of contacts on spin lifetime measurements in graphene
description: Effect of contacts on spin lifetime measurements in graphene
keywords: [deck.js, talk]
locale: en_US
site_name: evansosenko.com

# This meta data is optional.
# determiner: null
# image: http://razor-x.github.io/jekyll-and-deck.js/preview.png
# audio: http://razor-x.github.io/jekyll-and-deck.js/talk.mp3
# video: http://razor-x.github.io/jekyll-and-deck.js/talk.mpg
# type: website
#
twitter:
  card: summary
  site: "@evansosenko"
  creator: "@evansosenko"
