---
# This meta data should be filled out.
title: Effect of contacts on spin lifetime measurements in graphene
description: Contributed Talk, APS March Meeting March 2014, Denver, CO, US.
keywords:
  - spintronics
  - spin
  - spin lifetime
  - graphene
  - Hanle effect
  - aps march meeting
  - 2014
  - physics
  - deck.js
  - talk
locale: en_US
site_name: evansosenko.com
color: "#3f51b5"

# This meta data is optional.
# determiner: null
image: https://io.evansosenko.com/deck-spin-lifetime/device.png
# audio: https://razor-x.github.io/jekyll-and-deck.js/talk.mp3
# video: https://razor-x.github.io/jekyll-and-deck.js/talk.mpg
# type: website
#
twitter:
  card: summary
  site: "@evansosenko"
  creator: "@evansosenko"
